#!/bin/bash

PATH="$HOME/.local/bin:$PATH"

trayer --edge top --align right --SetDockType true --SetPartialStrut true --expand true --width 10 --transparent true --tint 0x191970 --height 17&

nm-applet&

# lock after 10 minutes of idle
xautolock -time 10 -locker "xtrlock -b" -notify 10 -notifier "notify-send -t 3000 -i gtk-dialog-info 'Locking in 10 seconds'" &

exec xmonad
