#!/bin/bash

export PATH="$HOME/.local/bin:$PATH"
if [ -e /home/abaw/.nix-profile/etc/profile.d/nix.sh ]; then . /home/abaw/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer

export GTK_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus
ibus-daemon -drx

trayer --edge top --align right --SetDockType true --SetPartialStrut true --expand true --width 10 --transparent true --tint 0x191970 --height 17&

nm-applet&

# lock after 10 minutes of idle
xautolock -time 10 -locker "xtrlock -b" -notify 10 -notifier "notify-send -t 3000 -i gtk-dialog-info 'Locking in 10 seconds'" &

# disable touchpad
synclient TouchPadOff=1

eval $(ssh-agent)

exec xmonad
