#!/bin/sh

# automatically change location
HAS_ETH=
CURRENT_LOCATION=$(networksetup -getcurrentlocation)
NEW_LOCATION=
networksetup -listallhardwareports| grep -q -F 'Hardware Port: Thunderbolt Ethernet' && HAS_ETH=YES


if [ -n "$HAS_ETH" ]; then
    NEW_LOCATION=Home
else
    NEW_LOCATION=Office
fi

if [ -n "$NEW_LOCATION" -a "$NEW_LOCATION" != "$CURRENT_LOCATION" ]; then
    logger -s -t wakeup "Switching location from '$CURRENT_LOCATION' to '$NEW_LOCATION'"
    scselect "$NEW_LOCATION"
fi
